import { APP_DEFAULT_LANG } from "../../../../lib/constants";

const en = {
    firstName: "First name",
    lastName: "Last name",
    gender: "Gender",
    male: "Male",
    female: "Female",
    other: "Other",
    dob: "Date of birth",
    email: "Email",
    country: "Country",
    city: "City",
    enter: "Enter",
    selectOrEnter: "Select or enter",
    startTyping: "Start typing",
    select: "Select",
    ddmmyy: "DD/MM/YY",
    next: "Next",
    loadingText: "Loading...",
    personalInformation: "Personal information",
    save: "Save",
    apply: "Apply",
    ageRange: "Age range",
    minAge: "Min age",
    maxAge: "Max age",
    filters: "Filters",
    noContacts: "No contacts",
    reset: "Reset",
    welcome: "Welcome!",
    back: "back",
    resendCode: "Resend code",
    enterYourPhoneNumber: "Enter your phone number to start using",
    phoneNumber: "Phone number",
    verificationCodeResent: "Verification code resent",
    sentVerificationCode: "We sent you verification code on",
    phoneNumberExample: "Eg. 98334234",
    search: "Search",
    allCountries: "All countries",
    usePushNotificationService: "Use push notification service ?",
    enablePushManually:
        "Please enable push notification manually in your browser to use this feature.",
    ok: "Ok",
    newGroupChat: "New group chat",
    selectMembers: "Select members",
    groupMembers: "Group members",
    create: "Create",
    groupName: "Group name",
    peopleSelected: "people selected",
    results: "results",
    settings: "Settings",
    enableDesktopNotifications: "Enable desktop notifications",
    logout: "Logout",
    uploadPhoto: "Upload photo",
    removePhoto: "Remove photo",
    photo: "Photo",
    confirm: "Confirm",
    noChats: "No chats",
    now: "now",
    chatDetails: "Chat details",
    groupDetails: "Group details",
    notes: "Notes",
    newNote: "New note",
    editNote: "Edit note",
    linkCopied: "Link copied",
    noteNotFound: "Note not found!",
    areYouSure: "Are you sure?",
    yesDelete: "Yes, delete",
    muteNotifications: "Mute notifications",
    members: "Members",
    admin: "Admin",
    bot: "Bot",
    makeAdmin: "Make admin",
    addMembers: "Add members",
    add: "Add",
    cantLeaveAdminGroup: "Can't leave group where you are only admin",
    unavailableAction: "Unavailable action",
    leaveGroupQuestion: "Leave group?",
    deleteGroupQuestion: "Delete group?",
    cancel: "Cancel",
    blockUser: "Block user",
    exitGroup: "Exit group",
    deleteGroup: "Delete group",
    notValidUrl: "Not valid URL",
    webhook: "Webhook",
    verifySignature: "Verify signature",
    remove: "Remove",
    apiKey: "API key",
    displayName: "Display name",
    postUrl: "POST URL",
    title: "Title",
    description: "Description",
    noNotes: "No notes here!",
    yearsOld: "years old",
};

const hr = {
    firstName: "Ime",
    lastName: "Prezime",
    gender: "Spol",
    male: "Muško",
    female: "Žensko",
    other: "Ostalo",
    dob: "Datum rođenja",
    email: "Email",
    country: "Država",
    city: "Grad",
    enter: "Unesi",
    selectOrEnter: "Odaberi ili unesi",
    startTyping: "Kreni pisati",
    select: "Odaberi",
    ddmmyy: "DD/MM/GG",
    next: "Dalje",
    loadingText: "Učitavanje...",
    personalInformation: "Osobne informacije",
    save: "Spremi",
    apply: "Primjeni",
    ageRange: "Raspon godina",
    minAge: "Min. godina",
    maxAge: "Maks. godina",
    filters: "Filteri",
    noContacts: "Nema kontakata",
    reset: "Reset",
    welcome: "Dobrodošli!",
    back: "nazad",
    resendCode: "Ponovo pošalji kod",
    enterYourPhoneNumber: "Unesi svoj broj telefona i kreni koristiti",
    phoneNumber: "Broj telefona",
    verificationCodeResent: "Kod za verifikaciju poslan",
    sentVerificationCode: "Poslali smo kod na",
    phoneNumberExample: "Npr. 098334234",
    search: "Traži",
    allCountries: "Sve zemlje",
    usePushNotificationService: "Koristi servis za push obavijesti?",
    enablePushManually:
        "Molimo omogućite servis za push obavijesti u svom pregledniku da biste mogli koristiti ovu funkcionalnost.",
    ok: "U redu",
    newGroupChat: "Novi grupni razgovor",
    selectMembers: "Odaberi članove",
    groupMembers: "Članovi grupe",
    create: "Kreiraj",
    groupName: "Ime grupe",
    peopleSelected: "odabrano osoba",
    results: "rezultati",
    settings: "Postavke",
    enableDesktopNotifications: "Omogući obavijesti",
    logout: "Odjava",
    uploadPhoto: "Učitaj sliku",
    removePhoto: "Ukloni sliku",
    photo: "Slika",
    confirm: "Potvrda",
    noChats: "Nema razgovora",
    now: "sada",
    chatDetails: "Detalji razgovora",
    groupDetails: "Detalji grupe",
    notes: "Bilješke",
    newNote: "Nova bilješka",
    editNote: "Uredi bilješku",
    linkCopied: "Link kopiran",
    noteNotFound: "Bilješka nije pronađena!",
    areYouSure: "Da li ste sigurni?",
    yesDelete: "Da, obriši",
    muteNotifications: "Utišaj obavijesti",
    members: "Članovi",
    admin: "Administrator",
    bot: "Bot",
    makeAdmin: "Postavi za admina",
    addMembers: "Dodaj članove",
    add: "Dodaj",
    cantLeaveAdminGroup: "Nije moguće napustiti grupu kada ste zadnji administrator u njoj",
    unavailableAction: "Nemoguća akcija",
    leaveGroupQuestion: "Napustiti grupu?",
    deleteGroupQuestion: "Obrisati grupu?",
    cancel: "Odustani",
    blockUser: "Blokiraj korisnika",
    exitGroup: "Napusti grupu",
    deleteGroup: "Obrisati grupu",
    notValidUrl: "Nije validan URL",
    webhook: "Webhook",
    verifySignature: "Sigurnosni potpis",
    remove: "Ukloni",
    apiKey: "API ključ",
    displayName: "Ime",
    postUrl: "POST URL",
    title: "Naslov",
    description: "Opis",
    noNotes: "Ovdje nema bilješki!",
    yearsOld: "godina",
};

const strings = {
    en,
    hr,
};

export default function useStrings() {
    return strings[APP_DEFAULT_LANG];
}
