import { APP_DEFAULT_LANG } from "../../../../lib/constants";

const en = {
    firstName: "First name",
    lastName: "Last name",
    gender: "Gender",
    male: "Male",
    female: "Female",
    other: "Other",
    dob: "Date of birth",
    email: "Email",
    country: "Country",
    city: "City",
    enter: "Enter",
    selectOrEnter: "Select or enter",
    startTyping: "Start typing",
    select: "Select",
    ddmmyy: "DD/MM/YY",
    next: "Next",
    loadingText: "Loading...",
    personalInformation: "Personal information",
    save: "Save",
    apply: "Apply",
    ageRange: "Age range",
    minAge: "Min age",
    maxAge: "Max age",
    filters: "Filters",
    noContacts: "No contacts",
    noRooms: "No rooms",
    reset: "Reset",
    welcome: "Welcome!",
    back: "back",
    resendCode: "Resend code",
    enterYourPhoneNumber: "Enter your phone number to start using",
    phoneNumber: "Phone number",
    verificationCodeResent: "Verification code resent",
    sentVerificationCode: "We sent you verification code on",
    phoneNumberExample: "Eg. 98334234",
    search: "Search",
    allCountries: "All countries",
    usePushNotificationService: "Use push notification service?",
    enablePushManually:
        "Please enable push notification manually in your browser to use this feature.",
    ok: "Ok",
    newGroupChat: "New group chat",
    selectMembers: "Select members",
    groupMembers: "Group members",
    create: "Create",
    groupName: "Group name",
    peopleSelected: "people selected",
    results: "results",
    settings: "Settings",
    enableDesktopNotifications: "Enable desktop notifications",
    logout: "Logout",
    uploadPhoto: "Upload photo",
    removePhoto: "Remove photo",
    photo: "Photo",
    confirm: "Confirm",
    noChats: "No chats",
    now: "now",
    chatDetails: "Chat details",
    groupDetails: "Group details",
    notes: "Notes",
    newNote: "New note",
    editNote: "Edit note",
    linkCopied: "Link copied",
    noteNotFound: "Note not found!",
    areYouSure: "Are you sure?",
    yesDelete: "Yes, delete",
    muteNotifications: "Mute notifications",
    members: "Members",
    admin: "Admin",
    bot: "Bot",
    makeAdmin: "Make admin",
    addMembers: "Add members",
    add: "Add",
    cantLeaveAdminGroup: "Can't leave group where you are only admin",
    unavailableAction: "Unavailable action",
    leaveGroupQuestion: "Leave group?",
    deleteGroupQuestion: "Delete group?",
    cancel: "Cancel",
    blockUser: "Block user",
    exitGroup: "Exit group",
    deleteGroup: "Delete group",
    notValidUrl: "Not valid URL",
    webhook: "Webhook",
    verifySignature: "Verify signature",
    remove: "Remove",
    apiKey: "API key",
    displayName: "Display name",
    postUrl: "POST URL",
    title: "Title",
    description: "Description",
    noNotes: "No notes here!",
    username: "Username",
    colorSchema: "Color schema",
    shared: "shared",
    removedUser: "Removed user",
    url: "Url",
    typeHere: "Type here",
    files: "Files",
    images: "Images",
    delete: "Delete",
    deleteForMe: "Delete for me",
    deleteForEveryone: "Delete for everyone",
    details: "Details",
    messageSentAt: "Message sent at",
    messageEditedAt: "Message edited at",
    readBy: "Read by",
    deliveredTo: "Delivered to",
    blockedUsers: "Blocked users",
    blockUserQuestion: "Do you want to block user?",
    noBlockedUsers: "No blocked users",
    youBlockedThisContact: "You blocked this contact.",
    clickHereToUnblock: "Click here to unblock.",
    yes: "Yes",
    goToChat: "Go to chat",
    showMore: "Show more",
    showLess: "Show less",
    resend: "Send again",
    pinChat: "Pin chat",
    senderActions: "Sender actions",
};

const strings = {
    en,
};

export default function useStrings() {
    return strings[APP_DEFAULT_LANG];
}
