global:
    scrape_interval: 15s
    scrape_timeout: 10s
    evaluation_interval: 15s
alerting:
    alertmanagers:
        - static_configs:
              - targets: []
          scheme: http
          timeout: 10s
          api_version: v1
scrape_configs:
    - job_name: prometheus
      static_configs:
          - targets:
                - localhost:9090
    - job_name: server-1
      static_configs:
          - targets:
                - 1.2.3.4:9100
    - job_name: server-2
      static_configs:
          - targets:
                - 2.3.4.5:9100
