version: "3"

networks:
    monitoring:

services:
    grafana:
        container_name: loadTestGrafana
        image: grafana/grafana:latest
        environment:
            - GF_SECURITY_ADMIN_USER=admin
            - GF_SECURITY_ADMIN_PASSWORD=grafana
        ports:
            - "3000:3000"
        volumes:
            - ./grafana:/etc/grafana/provisioning/datasources
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1",
                ]
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - monitoring

    prometheus:
        image: prom/prometheus
        container_name: loadTestPrometheus
        command:
            - "--config.file=/etc/prometheus/prometheus.yml"
        ports:
            - 9090:9090
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "wget --no-verbose --tries=1 --spider http://localhost:9090/-/healthy || exit 1",
                ]
            interval: 10s
            timeout: 5s
            retries: 5
        volumes:
            - ./prometheus:/etc/prometheus
            - prom_data:/prometheus
        networks:
            - monitoring

volumes:
    prom_data:
    loki_data:
