export interface CountryType {
    code: string;
    labelEN: string;
    labelHR: string;
    labelES: string;
    labelDE: string;
    phone: string;
    suggested?: boolean;
}

const countries: CountryType[] = [
    {
        code: "AD",
        labelEN: "Andorra",
        labelHR: "Andora",
        labelES: "Andorra",
        labelDE: "Andorra",
        phone: "376",
    },
    {
        code: "AE",
        labelEN: "United Arab Emirates",
        labelHR: "Ujedinjeni Arapski Emirati",
        labelES: "Emiratos Árabes Unidos",
        labelDE: "Vereinigte Arabische Emirate",
        phone: "971",
    },
    {
        code: "AF",
        labelEN: "Afghanistan",
        labelHR: "Afganistan",
        labelES: "Afganistán",
        labelDE: "Afghanistan",
        phone: "93",
    },
    {
        code: "AG",
        labelEN: "Antigua and Barbuda",
        labelHR: "Antigva i Barbuda",
        labelES: "Antigua y Barbuda",
        labelDE: "Antigua und Barbuda",
        phone: "1-268",
    },
    {
        code: "AI",
        labelEN: "Anguilla",
        labelHR: "Angvila",
        labelES: "Anguila",
        labelDE: "Anguilla",
        phone: "1-264",
    },
    {
        code: "AL",
        labelEN: "Albania",
        labelHR: "Albanija",
        labelES: "Albania",
        labelDE: "Albanien",
        phone: "355",
    },
    {
        code: "AM",
        labelEN: "Armenia",
        labelHR: "Armenija",
        labelES: "Armenia",
        labelDE: "Armenien",
        phone: "374",
    },
    {
        code: "AO",
        labelEN: "Angola",
        labelHR: "Angola",
        labelES: "Angola",
        labelDE: "Angola",
        phone: "244",
    },
    {
        code: "AQ",
        labelEN: "Antarctica",
        labelHR: "Antarktika",
        labelES: "Antártida",
        labelDE: "Antarktis",
        phone: "672",
    },
    {
        code: "AR",
        labelEN: "Argentina",
        labelHR: "Argentina",
        labelES: "Argentina",
        labelDE: "Argentinien",
        phone: "54",
    },
    {
        code: "AS",
        labelEN: "American Samoa",
        labelHR: "Američka Samoa",
        labelES: "Samoa Americana",
        labelDE: "Amerikanisch-Samoa",
        phone: "1-684",
    },
    {
        code: "AT",
        labelEN: "Austria",
        labelHR: "Austrija",
        labelES: "Austria",
        labelDE: "Österreich",
        phone: "43",
    },
    {
        code: "AU",
        labelEN: "Australia",
        labelHR: "Australija",
        labelES: "Australia",
        labelDE: "Australien",
        phone: "61",
        suggested: true,
    },
    {
        code: "AW",
        labelEN: "Aruba",
        labelHR: "Aruba",
        labelES: "Aruba",
        labelDE: "Aruba",
        phone: "297",
    },
    {
        code: "AX",
        labelEN: "Alland Islands",
        labelHR: "Alandski otoci",
        labelES: "Islas Åland",
        labelDE: "Åland-Inseln",
        phone: "358",
    },
    {
        code: "AZ",
        labelEN: "Azerbaijan",
        labelHR: "Azerbajdžan",
        labelES: "Azerbaiyán",
        labelDE: "Aserbaidschan",
        phone: "994",
    },
    {
        code: "BA",
        labelEN: "Bosnia and Herzegovina",
        labelHR: "Bosna i Hercegovina",
        labelES: "Bosnia y Herzegovina",
        labelDE: "Bosnien und Herzegowina",
        phone: "387",
    },
    {
        code: "BB",
        labelEN: "Barbados",
        labelHR: "Barbados",
        labelES: "Barbados",
        labelDE: "Barbados",
        phone: "1-246",
    },
    {
        code: "BD",
        labelEN: "Bangladesh",
        labelHR: "Bangladeš",
        labelES: "Bangladés",
        labelDE: "Bangladesch",
        phone: "880",
    },
    {
        code: "BE",
        labelEN: "Belgium",
        labelHR: "Belgija",
        labelES: "Bélgica",
        labelDE: "Belgien",
        phone: "32",
    },
    {
        code: "BF",
        labelEN: "Burkina Faso",
        labelHR: "Burkina Faso",
        labelES: "Burkina Faso",
        labelDE: "Burkina Faso",
        phone: "226",
    },
    {
        code: "BG",
        labelEN: "Bulgaria",
        labelHR: "Bugarska",
        labelES: "Bulgaria",
        labelDE: "Bulgarien",
        phone: "359",
    },
    {
        code: "BH",
        labelEN: "Bahrain",
        labelHR: "Bahrein",
        labelES: "Baréin",
        labelDE: "Bahrain",
        phone: "973",
    },
    {
        code: "BI",
        labelEN: "Burundi",
        labelHR: "Burundi",
        labelES: "Burundi",
        labelDE: "Burundi",
        phone: "257",
    },
    {
        code: "BJ",
        labelEN: "Benin",
        labelHR: "Benin",
        labelES: "Benín",
        labelDE: "Benin",
        phone: "229",
    },
    {
        code: "BL",
        labelEN: "Saint Barthelemy",
        labelHR: "Sveti Bartolomej",
        labelES: "San Bartolomé",
        labelDE: "Saint-Barthélemy",
        phone: "590",
    },
    {
        code: "BM",
        labelEN: "Bermuda",
        labelHR: "Bermudi",
        labelES: "Bermudas",
        labelDE: "Bermuda",
        phone: "1-441",
    },
    {
        code: "BN",
        labelEN: "Brunei Darussalam",
        labelHR: "Brunej",
        labelES: "Brunéi",
        labelDE: "Brunei Darussalam",
        phone: "673",
    },
    {
        code: "BO",
        labelEN: "Bolivia",
        labelHR: "Bolivija",
        labelES: "Bolivia",
        labelDE: "Bolivien",
        phone: "591",
    },
    {
        code: "BR",
        labelEN: "Brazil",
        labelHR: "Brazil",
        labelES: "Brasil",
        labelDE: "Brasilien",
        phone: "55",
    },
    {
        code: "BS",
        labelEN: "Bahamas",
        labelHR: "Bahami",
        labelES: "Bahamas",
        labelDE: "Bahamas",
        phone: "1-242",
    },
    {
        code: "BT",
        labelEN: "Bhutan",
        labelHR: "Butan",
        labelES: "Bután",
        labelDE: "Bhutan",
        phone: "975",
    },
    {
        code: "BV",
        labelEN: "Bouvet Island",
        labelHR: "Otok Bouvet",
        labelES: "Isla Bouvet",
        labelDE: "Bouvetinsel",
        phone: "47",
    },
    {
        code: "BW",
        labelEN: "Botswana",
        labelHR: "Bocvana",
        labelES: "Botsuana",
        labelDE: "Botswana",
        phone: "267",
    },
    {
        code: "BY",
        labelEN: "Belarus",
        labelHR: "Bjelorusija",
        labelES: "Bielorrusia",
        labelDE: "Weißrussland",
        phone: "375",
    },
    {
        code: "BZ",
        labelEN: "Belize",
        labelHR: "Belize",
        labelES: "Belice",
        labelDE: "Belize",
        phone: "501",
    },
    {
        code: "CA",
        labelEN: "Canada",
        labelHR: "Kanada",
        labelES: "Canadá",
        labelDE: "Kanada",
        phone: "1",
        suggested: true,
    },
    {
        code: "CC",
        labelEN: "Cocos (Keeling) Islands",
        labelHR: "Kokosovi (Keelingovi) otoci",
        labelES: "Islas Cocos",
        labelDE: "Kokosinseln",
        phone: "61",
    },
    {
        code: "CD",
        labelEN: "Congo, Democratic Republic of the",
        labelHR: "Demokratska Republika Kongo",
        labelES: "República Democrática del Congo",
        labelDE: "Demokratische Republik Kongo",
        phone: "243",
    },
    {
        code: "CF",
        labelEN: "Central African Republic",
        labelHR: "Srednjoafrička Republika",
        labelES: "República Centroafricana",
        labelDE: "Zentralafrikanische Republik",
        phone: "236",
    },
    {
        code: "CG",
        labelEN: "Congo, Republic of the",
        labelHR: "Republika Kongo",
        labelES: "República del Congo",
        labelDE: "Republik Kongo",
        phone: "242",
    },
    {
        code: "CH",
        labelEN: "Switzerland",
        labelHR: "Švicarska",
        labelES: "Suiza",
        labelDE: "Schweiz",
        phone: "41",
    },

    {
        code: "CI",
        labelEN: "Cote d'Ivoire",
        labelHR: "Obala Bjelokosti",
        labelES: "Costa de Marfil",
        labelDE: "Elfenbeinküste",
        phone: "225",
    },
    {
        code: "CK",
        labelEN: "Cook Islands",
        labelHR: "Cookovi Otoci",
        labelES: "Islas Cook",
        labelDE: "Cookinseln",
        phone: "682",
    },
    {
        code: "CL",
        labelEN: "Chile",
        labelHR: "Čile",
        labelES: "Chile",
        labelDE: "Chile",
        phone: "56",
    },
    {
        code: "CM",
        labelEN: "Cameroon",
        labelHR: "Kamerun",
        labelES: "Camerún",
        labelDE: "Kamerun",
        phone: "237",
    },
    {
        code: "CN",
        labelEN: "China",
        labelHR: "Kina",
        labelES: "China",
        labelDE: "China",
        phone: "86",
    },
    {
        code: "CO",
        labelEN: "Colombia",
        labelHR: "Kolumbija",
        labelES: "Colombia",
        labelDE: "Kolumbien",
        phone: "57",
    },
    {
        code: "CR",
        labelEN: "Costa Rica",
        labelHR: "Kostarika",
        labelES: "Costa Rica",
        labelDE: "Costa Rica",
        phone: "506",
    },
    { code: "CU", labelEN: "Cuba", labelHR: "Kuba", labelES: "Cuba", labelDE: "Kuba", phone: "53" },
    {
        code: "CV",
        labelEN: "Cape Verde",
        labelHR: "Zelenortska Republika",
        labelES: "Cabo Verde",
        labelDE: "Kap Verde",
        phone: "238",
    },
    {
        code: "CW",
        labelEN: "Curacao",
        labelHR: "Curaçao",
        labelES: "Curazao",
        labelDE: "Curaçao",
        phone: "599",
    },
    {
        code: "CX",
        labelEN: "Christmas Island",
        labelHR: "Božićni otok",
        labelES: "Isla de Navidad",
        labelDE: "Weihnachtsinsel",
        phone: "61",
    },
    {
        code: "CY",
        labelEN: "Cyprus",
        labelHR: "Cipar",
        labelES: "Chipre",
        labelDE: "Zypern",
        phone: "357",
    },
    {
        code: "CZ",
        labelEN: "Czech Republic",
        labelHR: "Češka",
        labelES: "Chequia",
        labelDE: "Tschechische Republik",
        phone: "420",
    },
    {
        code: "DE",
        labelEN: "Germany",
        labelHR: "Njemačka",
        labelES: "Alemania",
        labelDE: "Deutschland",
        phone: "49",
        suggested: true,
    },
    {
        code: "DJ",
        labelEN: "Djibouti",
        labelHR: "Džibuti",
        labelES: "Yibuti",
        labelDE: "Dschibuti",
        phone: "253",
    },
    {
        code: "DK",
        labelEN: "Denmark",
        labelHR: "Danska",
        labelES: "Dinamarca",
        labelDE: "Dänemark",
        phone: "45",
    },
    {
        code: "DM",
        labelEN: "Dominica",
        labelHR: "Dominika",
        labelES: "Dominica",
        labelDE: "Dominica",
        phone: "1-767",
    },
    {
        code: "DO",
        labelEN: "Dominican Republic",
        labelHR: "Dominikanska Republika",
        labelES: "República Dominicana",
        labelDE: "Dominikanische Republik",
        phone: "1-809",
    },
    {
        code: "DZ",
        labelEN: "Algeria",
        labelHR: "Alžir",
        labelES: "Argelia",
        labelDE: "Algerien",
        phone: "213",
    },
    {
        code: "EC",
        labelEN: "Ecuador",
        labelHR: "Ekvador",
        labelES: "Ecuador",
        labelDE: "Ecuador",
        phone: "593",
    },
    {
        code: "EE",
        labelEN: "Estonia",
        labelHR: "Estonija",
        labelES: "Estonia",
        labelDE: "Estland",
        phone: "372",
    },
    {
        code: "EG",
        labelEN: "Egypt",
        labelHR: "Egipat",
        labelES: "Egipto",
        labelDE: "Ägypten",
        phone: "20",
    },
    {
        code: "EH",
        labelEN: "Western Sahara",
        labelHR: "Zapadna Sahara",
        labelES: "Sahara Occidental",
        labelDE: "Westsahara",
        phone: "212",
    },
    {
        code: "ER",
        labelEN: "Eritrea",
        labelHR: "Eritreja",
        labelES: "Eritrea",
        labelDE: "Eritrea",
        phone: "291",
    },
    {
        code: "ES",
        labelEN: "Spain",
        labelHR: "Španjolska",
        labelES: "España",
        labelDE: "Spanien",
        phone: "34",
        suggested: true,
    },
    {
        code: "ET",
        labelEN: "Ethiopia",
        labelHR: "Etiopija",
        labelES: "Etiopía",
        labelDE: "Äthiopien",
        phone: "251",
    },
    {
        code: "FI",
        labelEN: "Finland",
        labelHR: "Finska",
        labelES: "Finlandia",
        labelDE: "Finnland",
        phone: "358",
    },
    {
        code: "FJ",
        labelEN: "Fiji",
        labelHR: "Fidži",
        labelES: "Fiyi",
        labelDE: "Fidschi",
        phone: "679",
    },
    {
        code: "FK",
        labelEN: "Falkland Islands (Malvinas)",
        labelHR: "Falklandski Otoci (Malvini)",
        labelES: "Islas Malvinas",
        labelDE: "Falklandinseln",
        phone: "500",
    },
    {
        code: "FM",
        labelEN: "Micronesia, Federated States of",
        labelHR: "Savez Država Mikronezije",
        labelES: "Micronesia",
        labelDE: "Mikronesien",
        phone: "691",
    },
    {
        code: "FO",
        labelEN: "Faroe Islands",
        labelHR: "Farski Otoci",
        labelES: "Islas Feroe",
        labelDE: "Färöer-Inseln",
        phone: "298",
    },
    {
        code: "FR",
        labelEN: "France",
        labelHR: "Francuska",
        labelES: "Francia",
        labelDE: "Frankreich",
        phone: "33",
        suggested: true,
    },
    {
        code: "GA",
        labelEN: "Gabon",
        labelHR: "Gabon",
        labelES: "Gabón",
        labelDE: "Gabun",
        phone: "241",
    },
    {
        code: "GB",
        labelEN: "United Kingdom",
        labelHR: "Ujedinjeno Kraljevstvo",
        labelES: "Reino Unido",
        labelDE: "Vereinigtes Königreich",
        phone: "44",
    },
    {
        code: "GD",
        labelEN: "Grenada",
        labelHR: "Grenada",
        labelES: "Granada",
        labelDE: "Grenada",
        phone: "1-473",
    },
    {
        code: "GE",
        labelEN: "Georgia",
        labelHR: "Gruzija",
        labelES: "Georgia",
        labelDE: "Georgien",
        phone: "995",
    },
    {
        code: "GF",
        labelEN: "French Guiana",
        labelHR: "Francuska Gvajana",
        labelES: "Guayana Francesa",
        labelDE: "Französisch-Guayana",
        phone: "594",
    },
    {
        code: "GG",
        labelEN: "Guernsey",
        labelHR: "Guernsey",
        labelES: "Guernsey",
        labelDE: "Guernsey",
        phone: "44",
    },
    {
        code: "GH",
        labelEN: "Ghana",
        labelHR: "Gana",
        labelES: "Ghana",
        labelDE: "Ghana",
        phone: "233",
    },
    {
        code: "GI",
        labelEN: "Gibraltar",
        labelHR: "Gibraltar",
        labelES: "Gibraltar",
        labelDE: "Gibraltar",
        phone: "350",
    },
    {
        code: "GL",
        labelEN: "Greenland",
        labelHR: "Grenland",
        labelES: "Groenlandia",
        labelDE: "Grönland",
        phone: "299",
    },
    {
        code: "GM",
        labelEN: "Gambia",
        labelHR: "Gambija",
        labelES: "Gambia",
        labelDE: "Gambia",
        phone: "220",
    },
    {
        code: "GN",
        labelEN: "Guinea",
        labelHR: "Gvineja",
        labelES: "Guinea",
        labelDE: "Guinea",
        phone: "224",
    },
    {
        code: "GP",
        labelEN: "Guadeloupe",
        labelHR: "Gvadalupa",
        labelES: "Guadalupe",
        labelDE: "Guadeloupe",
        phone: "590",
    },
    {
        code: "GQ",
        labelEN: "Equatorial Guinea",
        labelHR: "Ekvatorska Gvineja",
        labelES: "Guinea Ecuatorial",
        labelDE: "Äquatorialguinea",
        phone: "240",
    },
    {
        code: "GR",
        labelEN: "Greece",
        labelHR: "Grčka",
        labelES: "Grecia",
        labelDE: "Griechenland",
        phone: "30",
    },
    {
        code: "GT",
        labelEN: "Guatemala",
        labelHR: "Gvatemala",
        labelES: "Guatemala",
        labelDE: "Guatemala",
        phone: "502",
    },
    {
        code: "GU",
        labelEN: "Guam",
        labelHR: "Guam",
        labelES: "Guam",
        labelDE: "Guam",
        phone: "1-671",
    },
    {
        code: "GW",
        labelEN: "Guinea-Bissau",
        labelHR: "Gvineja Bisau",
        labelES: "Guinea-Bisáu",
        labelDE: "Guinea-Bissau",
        phone: "245",
    },
    {
        code: "GY",
        labelEN: "Guyana",
        labelHR: "Gvajana",
        labelES: "Guyana",
        labelDE: "Guyana",
        phone: "592",
    },
    {
        code: "HK",
        labelEN: "Hong Kong",
        labelHR: "Hong Kong",
        labelES: "Hong Kong",
        labelDE: "Hongkong",
        phone: "852",
    },
    {
        code: "HM",
        labelEN: "Heard Island and McDonald Islands",
        labelHR: "Otok Heard i otočje McDonald",
        labelES: "Islas Heard y McDonald",
        labelDE: "Heard und McDonaldinseln",
        phone: "672",
    },
    {
        code: "HN",
        labelEN: "Honduras",
        labelHR: "Honduras",
        labelES: "Honduras",
        labelDE: "Honduras",
        phone: "504",
    },
    {
        code: "HR",
        labelEN: "Croatia",
        labelHR: "Hrvatska",
        labelES: "Croacia",
        labelDE: "Kroatien",
        phone: "385",
    },
    {
        code: "HT",
        labelEN: "Haiti",
        labelHR: "Haiti",
        labelES: "Haití",
        labelDE: "Haiti",
        phone: "509",
    },
    {
        code: "HU",
        labelEN: "Hungary",
        labelHR: "Mađarska",
        labelES: "Hungría",
        labelDE: "Ungarn",
        phone: "36",
    },
    {
        code: "ID",
        labelEN: "Indonesia",
        labelHR: "Indonezija",
        labelES: "Indonesia",
        labelDE: "Indonesien",
        phone: "62",
    },
    {
        code: "IE",
        labelEN: "Ireland",
        labelHR: "Irska",
        labelES: "Irlanda",
        labelDE: "Irland",
        phone: "353",
    },
    {
        code: "IL",
        labelEN: "Israel",
        labelHR: "Izrael",
        labelES: "Israel",
        labelDE: "Israel",
        phone: "972",
    },
    {
        code: "IM",
        labelEN: "Isle of Man",
        labelHR: "Otok Man",
        labelES: "Isla de Man",
        labelDE: "Isle of Man",
        phone: "44",
    },
    {
        code: "IN",
        labelEN: "India",
        labelHR: "Indija",
        labelES: "India",
        labelDE: "Indien",
        phone: "91",
    },
    {
        code: "IO",
        labelEN: "British Indian Ocean Territory",
        labelHR: "Britanski Indijskooceanski teritorij",
        labelES: "Territorio Británico del Océano Índico",
        labelDE: "Britisches Territorium im Indischen Ozean",
        phone: "246",
    },
    {
        code: "IQ",
        labelEN: "Iraq",
        labelHR: "Irak",
        labelES: "Iraq",
        labelDE: "Irak",
        phone: "964",
    },
    {
        code: "IR",
        labelEN: "Iran, Islamic Republic of",
        labelHR: "Iran",
        labelES: "Irán",
        labelDE: "Iran",
        phone: "98",
    },
    {
        code: "IS",
        labelEN: "Iceland",
        labelHR: "Island",
        labelES: "Islandia",
        labelDE: "Island",
        phone: "354",
    },
    {
        code: "IT",
        labelEN: "Italy",
        labelHR: "Italija",
        labelES: "Italia",
        labelDE: "Italien",
        phone: "39",
        suggested: true,
    },
    {
        code: "JE",
        labelEN: "Jersey",
        labelHR: "Jersey",
        labelES: "Jersey",
        labelDE: "Jersey",
        phone: "44",
    },
    {
        code: "JM",
        labelEN: "Jamaica",
        labelHR: "Jamajka",
        labelES: "Jamaica",
        labelDE: "Jamaika",
        phone: "1-876",
    },
    {
        code: "JO",
        labelEN: "Jordan",
        labelHR: "Jordan",
        labelES: "Jordania",
        labelDE: "Jordanien",
        phone: "962",
    },
    {
        code: "JP",
        labelEN: "Japan",
        labelHR: "Japan",
        labelES: "Japón",
        labelDE: "Japan",
        phone: "81",
    },
    {
        code: "KE",
        labelEN: "Kenya",
        labelHR: "Kenija",
        labelES: "Kenia",
        labelDE: "Kenia",
        phone: "254",
    },
    {
        code: "KG",
        labelEN: "Kyrgyzstan",
        labelHR: "Kirgistan",
        labelES: "Kirguistán",
        labelDE: "Kirgisistan",
        phone: "996",
    },
    {
        code: "KH",
        labelEN: "Cambodia",
        labelHR: "Kambodža",
        labelES: "Camboya",
        labelDE: "Kambodscha",
        phone: "855",
    },
    {
        code: "KI",
        labelEN: "Kiribati",
        labelHR: "Kiribati",
        labelES: "Kiribati",
        labelDE: "Kiribati",
        phone: "686",
    },
    {
        code: "KM",
        labelEN: "Comoros",
        labelHR: "Komori",
        labelES: "Comoras",
        labelDE: "Komoren",
        phone: "269",
    },
    {
        code: "KN",
        labelEN: "Saint Kitts and Nevis",
        labelHR: "Sveti Kristofor i Nevis",
        labelES: "San Cristóbal y Nieves",
        labelDE: "St. Kitts und Nevis",
        phone: "1-869",
    },
    {
        code: "KP",
        labelEN: "Korea, Democratic People's Republic of",
        labelHR: "Sjeverna Koreja",
        labelES: "Corea del Norte",
        labelDE: "Nordkorea",
        phone: "850",
    },
    {
        code: "KR",
        labelEN: "Korea, Republic of",
        labelHR: "Južna Koreja",
        labelES: "Corea del Sur",
        labelDE: "Südkorea",
        phone: "82",
    },
    {
        code: "KW",
        labelEN: "Kuwait",
        labelHR: "Kuvajt",
        labelES: "Kuwait",
        labelDE: "Kuwait",
        phone: "965",
    },
    {
        code: "KY",
        labelEN: "Cayman Islands",
        labelHR: "Kajmanski Otoci",
        labelES: "Islas Caimán",
        labelDE: "Kaimaninseln",
        phone: "1-345",
    },
    {
        code: "KZ",
        labelEN: "Kazakhstan",
        labelHR: "Kazahstan",
        labelES: "Kazajistán",
        labelDE: "Kasachstan",
        phone: "7",
    },
    {
        code: "LA",
        labelEN: "Lao People's Democratic Republic",
        labelHR: "Laos",
        labelES: "Laos",
        labelDE: "Laos",
        phone: "856",
    },
    {
        code: "LB",
        labelEN: "Lebanon",
        labelHR: "Libanon",
        labelES: "Líbano",
        labelDE: "Libanon",
        phone: "961",
    },
    {
        code: "LC",
        labelEN: "Saint Lucia",
        labelHR: "Sveta Lucija",
        labelES: "Santa Lucía",
        labelDE: "St. Lucia",
        phone: "1-758",
    },
    {
        code: "LI",
        labelEN: "Liechtenstein",
        labelHR: "Lihtenštajn",
        labelES: "Liechtenstein",
        labelDE: "Liechtenstein",
        phone: "423",
    },
    {
        code: "LK",
        labelEN: "Sri Lanka",
        labelHR: "Šri Lanka",
        labelES: "Sri Lanka",
        labelDE: "Sri Lanka",
        phone: "94",
    },
    {
        code: "LR",
        labelEN: "Liberia",
        labelHR: "Liberija",
        labelES: "Liberia",
        labelDE: "Liberia",
        phone: "231",
    },
    {
        code: "LS",
        labelEN: "Lesotho",
        labelHR: "Lesoto",
        labelES: "Lesotho",
        labelDE: "Lesotho",
        phone: "266",
    },
    {
        code: "LT",
        labelEN: "Lithuania",
        labelHR: "Litva",
        labelES: "Lituania",
        labelDE: "Litauen",
        phone: "370",
    },
    {
        code: "LU",
        labelEN: "Luxembourg",
        labelHR: "Luksemburg",
        labelES: "Luxemburgo",
        labelDE: "Luxemburg",
        phone: "352",
    },
    {
        code: "LV",
        labelEN: "Latvia",
        labelHR: "Latvija",
        labelES: "Letonia",
        labelDE: "Lettland",
        phone: "371",
    },
    {
        code: "LY",
        labelEN: "Libya",
        labelHR: "Libija",
        labelES: "Libia",
        labelDE: "Libyen",
        phone: "218",
    },
    {
        code: "MA",
        labelEN: "Morocco",
        labelHR: "Maroko",
        labelES: "Marruecos",
        labelDE: "Marokko",
        phone: "212",
    },
    {
        code: "MC",
        labelEN: "Monaco",
        labelHR: "Monako",
        labelES: "Mónaco",
        labelDE: "Monaco",
        phone: "377",
    },
    {
        code: "MD",
        labelEN: "Moldova, Republic of",
        labelHR: "Moldova",
        labelES: "Moldavia",
        labelDE: "Moldawien",
        phone: "373",
    },
    {
        code: "ME",
        labelEN: "Montenegro",
        labelHR: "Crna Gora",
        labelES: "Montenegro",
        labelDE: "Montenegro",
        phone: "382",
    },
    {
        code: "MF",
        labelEN: "Saint Martin (French part)",
        labelHR: "Sveti Martin (francuski dio)",
        labelES: "San Martín (parte francesa)",
        labelDE: "Saint-Martin (französischer Teil)",
        phone: "590",
    },
    {
        code: "MG",
        labelEN: "Madagascar",
        labelHR: "Madagaskar",
        labelES: "Madagascar",
        labelDE: "Madagaskar",
        phone: "261",
    },
    {
        code: "MH",
        labelEN: "Marshall Islands",
        labelHR: "Maršalovi Otoci",
        labelES: "Islas Marshall",
        labelDE: "Marshallinseln",
        phone: "692",
    },
    {
        code: "MK",
        labelEN: "North Macedonia",
        labelHR: "Sjeverna Makedonija",
        labelES: "Macedonia del Norte",
        labelDE: "Nordmazedonien",
        phone: "389",
    },
    {
        code: "ML",
        labelEN: "Mali",
        labelHR: "Mali",
        labelES: "Mali",
        labelDE: "Mali",
        phone: "223",
    },
    {
        code: "MM",
        labelEN: "Myanmar",
        labelHR: "Mjanmar",
        labelES: "Myanmar",
        labelDE: "Myanmar",
        phone: "95",
    },
    {
        code: "MN",
        labelEN: "Mongolia",
        labelHR: "Mongolija",
        labelES: "Mongolia",
        labelDE: "Mongolei",
        phone: "976",
    },
    {
        code: "MO",
        labelEN: "Macao",
        labelHR: "Makao",
        labelES: "Macao",
        labelDE: "Macao",
        phone: "853",
    },
    {
        code: "MP",
        labelEN: "Northern Mariana Islands",
        labelHR: "Sjeverni Marijanski Otoci",
        labelES: "Islas Marianas del Norte",
        labelDE: "Nördliche Marianen",
        phone: "1-670",
    },
    {
        code: "MQ",
        labelEN: "Martinique",
        labelHR: "Martinique",
        labelES: "Martinica",
        labelDE: "Martinique",
        phone: "596",
    },
    {
        code: "MR",
        labelEN: "Mauritania",
        labelHR: "Mauritanija",
        labelES: "Mauritania",
        labelDE: "Mauretanien",
        phone: "222",
    },
    {
        code: "MS",
        labelEN: "Montserrat",
        labelHR: "Montserrat",
        labelES: "Montserrat",
        labelDE: "Montserrat",
        phone: "1-664",
    },
    {
        code: "MT",
        labelEN: "Malta",
        labelHR: "Malta",
        labelES: "Malta",
        labelDE: "Malta",
        phone: "356",
    },
    {
        code: "MU",
        labelEN: "Mauritius",
        labelHR: "Mauricijus",
        labelES: "Mauricio",
        labelDE: "Mauritius",
        phone: "230",
    },
    {
        code: "MV",
        labelEN: "Maldives",
        labelHR: "Maldivi",
        labelES: "Maldivas",
        labelDE: "Malediven",
        phone: "960",
    },
    {
        code: "MW",
        labelEN: "Malawi",
        labelHR: "Malavi",
        labelES: "Malawi",
        labelDE: "Malawi",
        phone: "265",
    },
    {
        code: "MX",
        labelEN: "Mexico",
        labelHR: "Meksiko",
        labelES: "México",
        labelDE: "Mexiko",
        phone: "52",
    },
    {
        code: "MY",
        labelEN: "Malaysia",
        labelHR: "Malezija",
        labelES: "Malasia",
        labelDE: "Malaysia",
        phone: "60",
    },
    {
        code: "MZ",
        labelEN: "Mozambique",
        labelHR: "Mozambik",
        labelES: "Mozambique",
        labelDE: "Mosambik",
        phone: "258",
    },
    {
        code: "NA",
        labelEN: "Namibia",
        labelHR: "Namibija",
        labelES: "Namibia",
        labelDE: "Namibia",
        phone: "264",
    },
    {
        code: "NC",
        labelEN: "New Caledonia",
        labelHR: "Nova Kaledonija",
        labelES: "Nueva Caledonia",
        labelDE: "Neukaledonien",
        phone: "687",
    },
    {
        code: "NE",
        labelEN: "Niger",
        labelHR: "Niger",
        labelES: "Níger",
        labelDE: "Niger",
        phone: "227",
    },
    {
        code: "NF",
        labelEN: "Norfolk Island",
        labelHR: "Otok Norfolk",
        labelES: "Isla Norfolk",
        labelDE: "Norfolkinsel",
        phone: "672",
    },
    {
        code: "NG",
        labelEN: "Nigeria",
        labelHR: "Nigerija",
        labelES: "Nigeria",
        labelDE: "Nigeria",
        phone: "234",
    },
    {
        code: "NI",
        labelEN: "Nicaragua",
        labelHR: "Nikaragva",
        labelES: "Nicaragua",
        labelDE: "Nicaragua",
        phone: "505",
    },
    {
        code: "NL",
        labelEN: "Netherlands",
        labelHR: "Nizozemska",
        labelES: "Países Bajos",
        labelDE: "Niederlande",
        phone: "31",
        suggested: true,
    },
    {
        code: "NO",
        labelEN: "Norway",
        labelHR: "Norveška",
        labelES: "Noruega",
        labelDE: "Norwegen",
        phone: "47",
    },
    {
        code: "NP",
        labelEN: "Nepal",
        labelHR: "Nepal",
        labelES: "Nepal",
        labelDE: "Nepal",
        phone: "977",
    },
    {
        code: "NR",
        labelEN: "Nauru",
        labelHR: "Nauru",
        labelES: "Nauru",
        labelDE: "Nauru",
        phone: "674",
    },
    {
        code: "NU",
        labelEN: "Niue",
        labelHR: "Niue",
        labelES: "Niue",
        labelDE: "Niue",
        phone: "683",
    },
    {
        code: "NZ",
        labelEN: "New Zealand",
        labelHR: "Novi Zeland",
        labelES: "Nueva Zelanda",
        labelDE: "Neuseeland",
        phone: "64",
    },
    {
        code: "OM",
        labelEN: "Oman",
        labelHR: "Oman",
        labelES: "Omán",
        labelDE: "Oman",
        phone: "968",
    },
    {
        code: "PA",
        labelEN: "Panama",
        labelHR: "Panama",
        labelES: "Panamá",
        labelDE: "Panama",
        phone: "507",
    },
    { code: "PE", labelEN: "Peru", labelHR: "Peru", labelES: "Perú", labelDE: "Peru", phone: "51" },
    {
        code: "PF",
        labelEN: "French Polynesia",
        labelHR: "Francuska Polinezija",
        labelES: "Polinesia Francesa",
        labelDE: "Französisch-Polynesien",
        phone: "689",
    },
    {
        code: "PG",
        labelEN: "Papua New Guinea",
        labelHR: "Papua Nova Gvineja",
        labelES: "Papúa Nueva Guinea",
        labelDE: "Papua-Neuguinea",
        phone: "675",
    },
    {
        code: "PH",
        labelEN: "Philippines",
        labelHR: "Filipini",
        labelES: "Filipinas",
        labelDE: "Philippinen",
        phone: "63",
    },
    {
        code: "PK",
        labelEN: "Pakistan",
        labelHR: "Pakistan",
        labelES: "Pakistán",
        labelDE: "Pakistan",
        phone: "92",
    },
    {
        code: "PL",
        labelEN: "Poland",
        labelHR: "Poljska",
        labelES: "Polonia",
        labelDE: "Polen",
        phone: "48",
    },
    {
        code: "PM",
        labelEN: "Saint Pierre and Miquelon",
        labelHR: "Sveti Petar i Mikelon",
        labelES: "San Pedro y Miquelón",
        labelDE: "St. Pierre und Miquelon",
        phone: "508",
    },
    {
        code: "PN",
        labelEN: "Pitcairn",
        labelHR: "Pitcairn",
        labelES: "Pitcairn",
        labelDE: "Pitcairninseln",
        phone: "870",
    },
    {
        code: "PR",
        labelEN: "Puerto Rico",
        labelHR: "Portoriko",
        labelES: "Puerto Rico",
        labelDE: "Puerto Rico",
        phone: "1",
    },
    {
        code: "PT",
        labelEN: "Portugal",
        labelHR: "Portugal",
        labelES: "Portugal",
        labelDE: "Portugal",
        phone: "351",
    },
    {
        code: "PW",
        labelEN: "Palau",
        labelHR: "Palau",
        labelES: "Palaos",
        labelDE: "Palau",
        phone: "680",
    },
    {
        code: "PY",
        labelEN: "Paraguay",
        labelHR: "Paragvaj",
        labelES: "Paraguay",
        labelDE: "Paraguay",
        phone: "595",
    },
    {
        code: "QA",
        labelEN: "Qatar",
        labelHR: "Katar",
        labelES: "Qatar",
        labelDE: "Katar",
        phone: "974",
    },
    {
        code: "RE",
        labelEN: "Réunion",
        labelHR: "Réunion",
        labelES: "Reunión",
        labelDE: "Réunion",
        phone: "262",
    },
    {
        code: "RO",
        labelEN: "Romania",
        labelHR: "Rumunjska",
        labelES: "Rumania",
        labelDE: "Rumänien",
        phone: "40",
    },
    {
        code: "RS",
        labelEN: "Serbia",
        labelHR: "Srbija",
        labelES: "Serbia",
        labelDE: "Serbien",
        phone: "381",
    },
    {
        code: "RU",
        labelEN: "Russian Federation",
        labelHR: "Rusija",
        labelES: "Rusia",
        labelDE: "Russland",
        phone: "7",
    },
    {
        code: "RW",
        labelEN: "Rwanda",
        labelHR: "Ruanda",
        labelES: "Ruanda",
        labelDE: "Ruanda",
        phone: "250",
    },
    {
        code: "SA",
        labelEN: "Saudi Arabia",
        labelHR: "Saudijska Arabija",
        labelES: "Arabia Saudí",
        labelDE: "Saudi-Arabien",
        phone: "966",
    },
    {
        code: "SB",
        labelEN: "Solomon Islands",
        labelHR: "Salomonski Otoci",
        labelES: "Islas Salomón",
        labelDE: "Salomonen",
        phone: "677",
    },
    {
        code: "SC",
        labelEN: "Seychelles",
        labelHR: "Sejšeli",
        labelES: "Seychelles",
        labelDE: "Seychellen",
        phone: "248",
    },
    {
        code: "SD",
        labelEN: "Sudan",
        labelHR: "Sudan",
        labelES: "Sudán",
        labelDE: "Sudan",
        phone: "249",
    },
    {
        code: "SE",
        labelEN: "Sweden",
        labelHR: "Švedska",
        labelES: "Suecia",
        labelDE: "Schweden",
        phone: "46",
    },
    {
        code: "SG",
        labelEN: "Singapore",
        labelHR: "Singapur",
        labelES: "Singapur",
        labelDE: "Singapur",
        phone: "65",
    },
    {
        code: "SH",
        labelEN: "Saint Helena",
        labelHR: "Sveta Helena",
        labelES: "Santa Elena",
        labelDE: "St. Helena",
        phone: "290",
    },
    {
        code: "SI",
        labelEN: "Slovenia",
        labelHR: "Slovenija",
        labelES: "Eslovenia",
        labelDE: "Slowenien",
        phone: "386",
    },
    {
        code: "SJ",
        labelEN: "Svalbard and Jan Mayen",
        labelHR: "Svalbard i Jan Mayen",
        labelES: "Svalbard y Jan Mayen",
        labelDE: "Svalbard und Jan Mayen",
        phone: "47",
    },
    {
        code: "SK",
        labelEN: "Slovakia",
        labelHR: "Slovačka",
        labelES: "Eslovaquia",
        labelDE: "Slowakei",
        phone: "421",
    },
    {
        code: "SL",
        labelEN: "Sierra Leone",
        labelHR: "Sijera Leone",
        labelES: "Sierra Leona",
        labelDE: "Sierra Leone",
        phone: "232",
    },
    {
        code: "SM",
        labelEN: "San Marino",
        labelHR: "San Marino",
        labelES: "San Marino",
        labelDE: "San Marino",
        phone: "378",
    },
    {
        code: "SN",
        labelEN: "Senegal",
        labelHR: "Senegal",
        labelES: "Senegal",
        labelDE: "Senegal",
        phone: "221",
    },
    {
        code: "SO",
        labelEN: "Somalia",
        labelHR: "Somalija",
        labelES: "Somalia",
        labelDE: "Somalia",
        phone: "252",
    },
    {
        code: "SR",
        labelEN: "Suriname",
        labelHR: "Surinam",
        labelES: "Surinam",
        labelDE: "Suriname",
        phone: "597",
    },
    {
        code: "SS",
        labelEN: "South Sudan",
        labelHR: "Južni Sudan",
        labelES: "Sudán del Sur",
        labelDE: "Südsudan",
        phone: "211",
    },
    {
        code: "ST",
        labelEN: "Sao Tome and Principe",
        labelHR: "Sveti Toma i Princip",
        labelES: "Santo Tomé y Príncipe",
        labelDE: "São Tomé und Príncipe",
        phone: "239",
    },
    {
        code: "SV",
        labelEN: "El Salvador",
        labelHR: "Salvador",
        labelES: "El Salvador",
        labelDE: "El Salvador",
        phone: "503",
    },
    {
        code: "SX",
        labelEN: "Sint Maarten (Dutch part)",
        labelHR: "Sint Maarten (nizozemski dio)",
        labelES: "Sint Maarten (parte holandesa)",
        labelDE: "Sint Maarten (niederländischer Teil)",
        phone: "1-721",
    },
    {
        code: "SY",
        labelEN: "Syrian Arab Republic",
        labelHR: "Sirija",
        labelES: "Siria",
        labelDE: "Syrien",
        phone: "963",
    },
    {
        code: "SZ",
        labelEN: "Swaziland",
        labelHR: "Svazi",
        labelES: "Suazilandia",
        labelDE: "Swasiland",
        phone: "268",
    },
    {
        code: "TC",
        labelEN: "Turks and Caicos Islands",
        labelHR: "Otoci Turks i Caicos",
        labelES: "Islas Turcas y Caicos",
        labelDE: "Turks- und Caicosinseln",
        phone: "1-649",
    },
    {
        code: "TD",
        labelEN: "Chad",
        labelHR: "Čad",
        labelES: "Chad",
        labelDE: "Tschad",
        phone: "235",
    },
    {
        code: "TF",
        labelEN: "French Southern Territories",
        labelHR: "Francuski južni teritoriji",
        labelES: "Tierras Australes Francesas",
        labelDE: "Französische Süd- und Antarktisgebiete",
        phone: "262",
    },
    {
        code: "TG",
        labelEN: "Togo",
        labelHR: "Togo",
        labelES: "Togo",
        labelDE: "Togo",
        phone: "228",
    },
    {
        code: "TH",
        labelEN: "Thailand",
        labelHR: "Tajland",
        labelES: "Tailandia",
        labelDE: "Thailand",
        phone: "66",
    },
    {
        code: "TJ",
        labelEN: "Tajikistan",
        labelHR: "Tadžikistan",
        labelES: "Tayikistán",
        labelDE: "Tadschikistan",
        phone: "992",
    },
    {
        code: "TK",
        labelEN: "Tokelau",
        labelHR: "Tokelau",
        labelES: "Tokelau",
        labelDE: "Tokelau",
        phone: "690",
    },
    {
        code: "TL",
        labelEN: "Timor-Leste",
        labelHR: "Timor-Leste",
        labelES: "Timor-Leste",
        labelDE: "Timor-Leste",
        phone: "670",
    },
    {
        code: "TM",
        labelEN: "Turkmenistan",
        labelHR: "Turkmenistan",
        labelES: "Turkmenistán",
        labelDE: "Turkmenistan",
        phone: "993",
    },
    {
        code: "TN",
        labelEN: "Tunisia",
        labelHR: "Tunis",
        labelES: "Túnez",
        labelDE: "Tunesien",
        phone: "216",
    },
    {
        code: "TO",
        labelEN: "Tonga",
        labelHR: "Tonga",
        labelES: "Tonga",
        labelDE: "Tonga",
        phone: "676",
    },
    {
        code: "TR",
        labelEN: "Turkey",
        labelHR: "Turska",
        labelES: "Turquía",
        labelDE: "Türkei",
        phone: "90",
    },
    {
        code: "TT",
        labelEN: "Trinidad and Tobago",
        labelHR: "Trinidad i Tobago",
        labelES: "Trinidad y Tobago",
        labelDE: "Trinidad und Tobago",
        phone: "1-868",
    },
    {
        code: "TV",
        labelEN: "Tuvalu",
        labelHR: "Tuvalu",
        labelES: "Tuvalu",
        labelDE: "Tuvalu",
        phone: "688",
    },
    {
        code: "TW",
        labelEN: "Taiwan, Province of China",
        labelHR: "Tajvan",
        labelES: "Taiwán",
        labelDE: "Taiwan",
        phone: "886",
    },
    {
        code: "TZ",
        labelEN: "United Republic of Tanzania",
        labelHR: "Tanzanija",
        labelES: "República Unida de Tanzania",
        labelDE: "Vereinigte Republik Tansania",
        phone: "255",
    },
    {
        code: "UA",
        labelEN: "Ukraine",
        labelHR: "Ukrajina",
        labelES: "Ucrania",
        labelDE: "Ukraine",
        phone: "380",
    },
    {
        code: "UG",
        labelEN: "Uganda",
        labelHR: "Uganda",
        labelES: "Uganda",
        labelDE: "Uganda",
        phone: "256",
    },
    {
        code: "US",
        labelEN: "United States",
        labelHR: "Sjedinjene Američke Države",
        labelES: "Estados Unidos",
        labelDE: "Vereinigte Staaten",
        phone: "1",
        suggested: true,
    },
    {
        code: "UY",
        labelEN: "Uruguay",
        labelHR: "Urugvaj",
        labelES: "Uruguay",
        labelDE: "Uruguay",
        phone: "598",
    },
    {
        code: "UZ",
        labelEN: "Uzbekistan",
        labelHR: "Uzbekistan",
        labelES: "Uzbekistán",
        labelDE: "Usbekistan",
        phone: "998",
    },
    {
        code: "VA",
        labelEN: "Holy See (Vatican City State)",
        labelHR: "Sveta Stolica (Vatikanski Grad)",
        labelES: "Santa Sede (Ciudad del Vaticano)",
        labelDE: "Heiliger Stuhl (Vatikanstadt)",
        phone: "379",
    },
    {
        code: "VC",
        labelEN: "Saint Vincent and the Grenadines",
        labelHR: "Saint Vincent i Grenadini",
        labelES: "San Vicente y las Granadinas",
        labelDE: "Saint Vincent und die Grenadinen",
        phone: "1-784",
    },
    {
        code: "VE",
        labelEN: "Venezuela",
        labelHR: "Venecuela",
        labelES: "Venezuela",
        labelDE: "Venezuela",
        phone: "58",
    },
    {
        code: "VG",
        labelEN: "British Virgin Islands",
        labelHR: "Britanski Djevičanski Otoci",
        labelES: "Islas Vírgenes Británicas",
        labelDE: "Britische Jungferninseln",
        phone: "1-284",
    },
    {
        code: "VI",
        labelEN: "US Virgin Islands",
        labelHR: "Američki Djevičanski Otoci",
        labelES: "Islas Vírgenes de los Estados Unidos",
        labelDE: "US-Jungferninseln",
        phone: "1-340",
    },
    {
        code: "VN",
        labelEN: "Vietnam",
        labelHR: "Vijetnam",
        labelES: "Vietnam",
        labelDE: "Vietnam",
        phone: "84",
    },
    {
        code: "VU",
        labelEN: "Vanuatu",
        labelHR: "Vanuatu",
        labelES: "Vanuatu",
        labelDE: "Vanuatu",
        phone: "678",
    },
    {
        code: "WF",
        labelEN: "Wallis and Futuna",
        labelHR: "Wallis i Futuna",
        labelES: "Wallis y Futuna",
        labelDE: "Wallis und Futuna",
        phone: "681",
    },
    {
        code: "WS",
        labelEN: "Samoa",
        labelHR: "Samoa",
        labelES: "Samoa",
        labelDE: "Samoa",
        phone: "685",
    },
    {
        code: "XK",
        labelEN: "Kosovo",
        labelHR: "Kosovo",
        labelES: "Kosovo",
        labelDE: "Kosovo",
        phone: "383",
    },
    {
        code: "YE",
        labelEN: "Yemen",
        labelHR: "Jemen",
        labelES: "Yemen",
        labelDE: "Jemen",
        phone: "967",
    },
    {
        code: "YT",
        labelEN: "Mayotte",
        labelHR: "Mayotte",
        labelES: "Mayotte",
        labelDE: "Mayotte",
        phone: "262",
    },
    {
        code: "ZA",
        labelEN: "South Africa",
        labelHR: "Južnoafrička Republika",
        labelES: "Sudáfrica",
        labelDE: "Südafrika",
        phone: "27",
    },
    {
        code: "ZM",
        labelEN: "Zambia",
        labelHR: "Zambija",
        labelES: "Zambia",
        labelDE: "Sambia",
        phone: "260",
    },
    {
        code: "ZW",
        labelEN: "Zimbabwe",
        labelHR: "Zelenortska Ostrva",
        labelES: "Zimbabue",
        labelDE: "Simbabwe",
        phone: "263",
    },
];

export default countries;
